import Link from 'next/link';
import { Bot, BarChart3, PenTool, ArrowRight } from 'lucide-react';

export default function Home() {
  return (
    <div className="min-h-screen bg-slate-50 flex items-center justify-center p-6">
      <div className="max-w-5xl w-full">
        <div className="text-center mb-16">
          <div className="inline-flex items-center justify-center p-3 bg-blue-600 rounded-2xl mb-6 shadow-lg shadow-blue-500/30">
            <Bot size={40} className="text-white" />
          </div>
          <h1 className="text-5xl md:text-6xl font-extrabold text-slate-900 tracking-tight">
            Digital Marketing <span className="text-transparent bg-clip-text bg-gradient-to-r from-blue-600 to-purple-600">AI Platform</span>
          </h1>
          <p className="text-xl text-slate-600 mt-6 max-w-2xl mx-auto">
            Your autonomous marketing agency. Manage leads, review AI-generated content, and scale your brand effortlessly.
          </p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
          {/* Module 1: BI Agent */}
          <Link href="/onboarding" className="group">
            <div className="bg-white p-8 rounded-3xl shadow-sm border border-slate-100 hover:shadow-xl hover:border-blue-100 transition-all duration-300 h-full flex flex-col">
              <div className="p-4 bg-blue-50 w-fit rounded-xl text-blue-600 mb-6 group-hover:scale-110 transition-transform">
                <Bot size={28} />
              </div>
              <h3 className="text-2xl font-bold text-slate-800 mb-3">1. AI Initialization</h3>
              <p className="text-slate-600 flex-grow mb-6">Train the Business Intelligence Agent on your exact brand tone and Ideal Customer Profile.</p>
              <div className="text-blue-600 font-semibold flex items-center gap-2 group-hover:gap-3 transition-all">
                Launch Wizard <ArrowRight size={18} />
              </div>
            </div>
          </Link>

          {/* Module 2: Content Agent */}
          <Link href="/approval" className="group">
            <div className="bg-white p-8 rounded-3xl shadow-sm border border-slate-100 hover:shadow-xl hover:border-purple-100 transition-all duration-300 h-full flex flex-col">
              <div className="p-4 bg-purple-50 w-fit rounded-xl text-purple-600 mb-6 group-hover:scale-110 transition-transform">
                <PenTool size={28} />
              </div>
              <h3 className="text-2xl font-bold text-slate-800 mb-3">2. Content Queue</h3>
              <p className="text-slate-600 flex-grow mb-6">Review, approve, or reject multi-platform social media posts and DALL-E 3 creatives generated by the AI.</p>
              <div className="text-purple-600 font-semibold flex items-center gap-2 group-hover:gap-3 transition-all">
                View Queue <ArrowRight size={18} />
              </div>
            </div>
          </Link>

          {/* Module 3: Analytics */}
          <Link href="/dashboard" className="group">
            <div className="bg-white p-8 rounded-3xl shadow-sm border border-slate-100 hover:shadow-xl hover:border-green-100 transition-all duration-300 h-full flex flex-col">
              <div className="p-4 bg-green-50 w-fit rounded-xl text-green-600 mb-6 group-hover:scale-110 transition-transform">
                <BarChart3 size={28} />
              </div>
              <h3 className="text-2xl font-bold text-slate-800 mb-3">3. ROI Dashboard</h3>
              <p className="text-slate-600 flex-grow mb-6">Monitor live Return on Ad Spend (ROAS) and track targeted leads discovered by the AI.</p>
              <div className="text-green-600 font-semibold flex items-center gap-2 group-hover:gap-3 transition-all">
                Open Dashboard <ArrowRight size={18} />
              </div>
            </div>
          </Link>
        </div>
      </div>
    </div>
  );
}
