import os

base_dir = "d:\\Digiatalai"
folders = ["docs/features", "docs/phases"]
for folder in folders:
    os.makedirs(os.path.join(base_dir, folder), exist_ok=True)

docs = {
    "docs/features/01_business_intelligence.md": """
# Business Intelligence Agent

## Overview
This agent is the strategic foundation for all other agents. It is responsible for onboarding new businesses and building their Ideal Customer Profile (ICP).

## Key Responsibilities
- Analyze company data, industry, and competition provided during onboarding.
- Build an Ideal Customer Profile (ICP) including demographics, behaviors, and pain points.
- Produce a structured marketing brief that will be used by all other agents as their starting context.
- Continuously update the ICP based on the Learning Loop (Analytics Agent).

## Technical Requirements
- Next.js onboarding form to collect location, products, and brand assets.
- Pinecone/Weaviate (Vector DB) integration to store brand tone and context (RAG).
- OpenAI/Claude prompt design for structuring raw inputs into a clean JSON ICP.
""",
    "docs/features/02_customer_discovery.md": """
# Customer Discovery Agent

## Overview
Finds real potential customers across all digital platforms based on the business's ICP.

## Key Responsibilities
- Scan Google Search and Google Maps for relevant local queries (e.g., 'restaurants near me').
- Scan Instagram and LinkedIn for user behavior matching the ICP.
- Score each discovered lead from 0 to 100 based on the fit.
- Automatically add qualified leads to the internal PostgreSQL CRM.

## Technical Requirements
- Integrations: Google Places API, Apify (for Instagram/LinkedIn scraping), Apollo.io (for B2B).
- Lead Scoring Logic: LLM compares scraped profile data against the ICP.
""",
    "docs/features/03_content_generation.md": """
# Content Generation Agent

## Overview
Creates all text and image-based marketing content including posts, ads, and captions.

## Key Responsibilities
- Generate platform-specific posts (Instagram vs. Facebook vs. LinkedIn).
- Generate multiple variants of Ad Copy for A/B testing.
- Produce a weekly 7-day content calendar.
- Use the RAG knowledge base + Social Media trends + Content Templates to generate highly relevant posts.

## Technical Requirements
- LangGraph Orchestrator to sequence the generation tasks.
- Image Generation APIs (DALL-E 3 / Midjourney) for visual assets.
- Approval Queue UI in Next.js where business owners can review content before it gets published.
""",
    "docs/features/04_reel_video_generation.md": """
# Reel & Video Generation Agent

## Overview
Handles all short-form video content creation (Reels, TikToks, Shorts).

## Key Responsibilities
- Option 1 (MVP): AI writes the script, the business owner records the video, and the AI uploads it with captions.
- Option 2 (Hybrid): Business uploads raw disorganized video; AI edits it, adds subtitles and music.
- Option 3 (Full AI): AI creates full video using AI avatars and text-to-speech.

## Technical Requirements
- ElevenLabs API for Voice/Text-to-speech.
- HeyGen or Synthesia API for Avatars.
- FFmpeg or Remotion for programmatic video stitching and editing.
""",
    "docs/features/05_advertising.md": """
# Advertising Agent

## Overview
Runs, manages, and continuously optimizes paid campaigns on Meta and Google.

## Key Responsibilities
- Configure targeting, placements, and budget limit automatically.
- Run A/B tests on creatives (generated by the Content Agent).
- Auto-pause underperforming ads and scale budgets on winners.
- Generate Lookalike audiences based on leads that converted.

## Technical Requirements
- Meta Graph API (Ads Manager) integration.
- Google Ads API integration.
- Celery Task Queue to handle long-running background optimizations (cron jobs).
""",
    "docs/features/06_customer_support_omixa.md": """
# Customer Support Routing (Omixa AI)

## Overview
Handles inbound customer communications 24/7 by seamlessly integrating with the external Omixa AI platform.

## Key Responsibilities
- Monitor inbound DMs, comments, and form submissions on Instagram and Facebook.
- Immediately forward the raw message data and context to Omixa AI.
- Listen for responses from Omixa AI and route them back to the specific platform.

## Technical Requirements
- Webhook endpoints in FastAPI to receive Meta platform events.
- Direct API connection/Webhook integration to the Omixa AI platform.
- Mapping internal Lead IDs to Omixa AI session IDs.
""",
    "docs/features/07_analytics_learning.md": """
# Analytics & Learning Agent

## Overview
Measures all KPIs across the platform and creates a self-improving feedback loop (The Brain).

## Key Responsibilities
- Track ROAS, CTR, CPL, CAC, and engagement in real-time.
- Generate Weekly and Monthly executive reports for the Business Owner dashboard.
- 'Learning Loop': Analyze what content/ads worked best, and write these 'lessons' back into the Vector Database (RAG) so other agents get smarter over time.

## Technical Requirements
- Real-time aggregation queries in PostgreSQL.
- Scheduled analytics processing via Celery.
- LLM summarization of stats into actionable 'lessons learned'.
""",
    "docs/phases/phase_1_mvp.md": """
# Phase 1: MVP (Month 1-2)

## Goal
Establish the foundational AI brain, business onboarding, and basic versions of core agents (Content, Ads, Discovery, Support).

## Detailed Roadmap
1. **Infrastructure Setup**
   - Create Next.js and FastAPI boilerplate.
   - Set up PostgreSQL and Pinecone Vector DB.
2. **Business Intelligence Agent**
   - Basic Frontend Onboarding flow (form).
   - Backend LLM logic to format inputs into an ICP.
3. **Customer Discovery Agent**
   - Implementation of Google Search & Instagram basic scanning.
   - Lead scoring and CRM table setup.
4. **Content Generation Agent**
   - Text posts and ad copy logic.
   - Frontend "Approval Queue" dashboard.
5. **Customer Support (Omixa AI)**
   - Initial webhook connection to capture IG DMs and forward them to Omixa AI.
6. **Advertising Agent**
   - Meta Ads basic campaign launcher.
7. **Analytics Dashboard**
   - Read-only UI showing spend, leads, and basic ROAS tracking.
""",
    "docs/phases/phase_2_growth.md": """
# Phase 2: Growth (Month 3-4)

## Goal
Expand discovery platforms, implement video content (Reels), and automate A/B testing optimization.

## Detailed Roadmap
1. **Reel Generation Agent (Model 1 & 3)**
   - AI script generation for business owners to record.
   - AI automatic video editing for uploaded raw clips.
2. **Platform Expansion**
   - LinkedIn integration for B2B discovery and LinkedIn Ads.
   - Google Ads Search & Display campaigns.
3. **Advanced Advertising Loop**
   - A/B testing system with automatic winner detection.
4. **Content Scheduling**
   - Visual Content Calendar view.
   - Multi-platform auto-publishing scheduler.
5. **Reporting**
   - Automated AI-generated weekly email reports.
""",
    "docs/phases/phase_3_scale.md": """
# Phase 3: Scale (Month 5-6)

## Goal
Fully autonomous operations with advanced AI generation, predictive budgets, and deep platform integrations.

## Detailed Roadmap
1. **Full AI Video (Model 2)**
   - Complete video generation using AI Avatars (HeyGen) and Voice (ElevenLabs).
2. **Delivery App Optimization**
   - Specific optimizations for Swiggy / Zomato menus and photos.
3. **Omnichannel Support**
   - WhatsApp Business API auto-reply integration (via Omixa AI).
4. **Predictive Analytics**
   - Predictive budget allocation engine using historical ROAS data.
   - Self-improving Learning Layer: Updates RAG automatically from every campaign result.
5. **Mobile Accessibility**
   - React Native mobile app for business owners to monitor operations.
"""
}

for path, content in docs.items():
    file_path = os.path.join(base_dir, path)
    with open(file_path, 'w', encoding='utf-8') as f:
        f.write(content.strip() + "\\n")
print("Successfully generated all feature and phase documentation.")
