from sqlalchemy import Column, String, Integer, DateTime, JSON, ForeignKey, Float
from sqlalchemy.sql import func
from sqlalchemy.dialects.postgresql import UUID
import uuid
from .database import Base, engine

class Business(Base):
    __tablename__ = "businesses"

    id = Column(String, primary_key=True, default=lambda: str(uuid.uuid4()))
    name = Column(String, nullable=False)
    industry = Column(String)
    location = Column(String)
    tone_of_voice = Column(String)
    icp_json = Column(JSON, nullable=True) # The Ideal Customer Profile generated by AI
    
    # Phase 3.3: SaaS Billing Columns
    subscription_tier = Column(String, default="free") # free, basic, pro, scale
    stripe_customer_id = Column(String, nullable=True)
    ai_requests_limit = Column(Integer, default=100) # Prevents computational LLM abuse
    
    # Phase 3.4: White-Labeling Multi-Tenancy (Agency mode)
    custom_subdomain = Column(String, unique=True, nullable=True) # e.g. "acmecorp"
    primary_color = Column(String, default="#3B82F6") # Native Tailwind Blue-500 Fallback
    brand_logo_url = Column(String, nullable=True)

    created_at = Column(DateTime(timezone=True), server_default=func.now())

class Lead(Base):
    __tablename__ = "leads"

    id = Column(String, primary_key=True, default=lambda: str(uuid.uuid4()))
    business_id = Column(String, ForeignKey("businesses.id"), nullable=False)
    
    # Discovery Agent Data
    source_platform = Column(String) # Google Places, Instagram, LinkedIn
    name_or_username = Column(String)
    raw_bio_or_description = Column(String)
    contact_info = Column(JSON, nullable=True)
    
    # B2B Advanced Discovery Data (Phase 2.2)
    email = Column(String, nullable=True) # Validated via Hunter
    linkedin_url = Column(String, nullable=True)
    company_size = Column(String, nullable=True)
    
    # AI Scoring Engine Data
    ai_score = Column(Float, nullable=True) # 0 to 100
    ai_reason = Column(String, nullable=True)
    
    status = Column(String, default="new") # new, contacted, converted, rejected
    created_at = Column(DateTime(timezone=True), server_default=func.now())

class Content(Base):
    __tablename__ = "content"

    id = Column(String, primary_key=True, default=lambda: str(uuid.uuid4()))
    business_id = Column(String, ForeignKey("businesses.id"), nullable=False)
    
    type = Column(String) # post, ad_copy, caption
    platform = Column(String) # meta, linkedin, google
    body = Column(String)
    media_url = Column(String)
    status = Column(String, default="draft") # draft, approved, published
    created_at = Column(DateTime(timezone=True), server_default=func.now())

# Create all tables in the engine (This is for MVP, standard migrations via Alembic later)
Base.metadata.create_all(bind=engine)
